%---------------------------------------------------------
%--      Main program, run this to start the simulation
%--      Author: Jarmo Rantakokko
%--      Course: Scientific Computing II
%---------------------------------------------------------

clear all
close all

%-- Set up user interface
T=0.6; dt=0.0015; dx=0.01;
%u1_right=0.5;u2_right=0;u3_right=1.4275;
%u1_left=0.445;u2_left=0.311;u3_left=8.928;
u1_right=0.125;u2_right=0;u3_right=0.25;
u1_left=1;u2_left=0;u3_left=2.5;

nframes=num2str(min(floor(T/dt),50));
sol=[];tvec=[]; 
EndSession='BYE';
h     = figure('NumberTitle','off','Name','Solver');
par_x = 20;
par_y = 10;
rect1 = [par_x,par_y,100,20];
rect2 = [par_x+100,par_y,50,20];


%-- Solver parameters
uicontrol(h,'Style','text','string','Run time T' ...
   ,'Position',rect1+[0,60,0,0]);
uicontrol(h,'Style','text','string','Time step dt' ...
   ,'Position',rect1+[0,40,0,0]);
uicontrol(h,'Style','text','string','Step size dx' ...
   ,'Position',rect1+[0,20,0,0]);



T_ui  = uicontrol(h,'Style','edit','String',num2str(T) ...
       ,'Position',rect2+[0,60,0,0],'Callback',['sol=[];','fmat=[];']);
dt_ui  = uicontrol(h,'Style','edit','String',num2str(dt) ...
       ,'Position',rect2+[0,40,0,0],'Callback',['sol=[];','fmat=[];']);
dx_ui  = uicontrol(h,'Style','edit','String',num2str(dx) ...
       ,'Position',rect2+[0,20,0,0],'Callback',['sol=[];','fmat=[];']);
%delta_ui  = uicontrol(h,'Style','edit','String','0.0' ...
%		  ,'Position',rect2+[0,0,0,0], ...
%		   'Callback','sol=[];');

%-- Numerical method and plot variabel
uicontrol(h,'Style','text','string','Numerical scheme' ...
   ,'Position',rect1+[160,60,0,0]);
method_ui=uicontrol(h,'Style','popupmenu','string', ...
      'Leapfrog|Rusanov', ...
      'Position',rect1+[160,45,0,0],'Callback',['sol=[];','fmat=[];','frame=0;', ...
                    'set(plot_ui,''String'',num2str(frame));', ...
                    'show(dx,plotvar,frame,sol,tvec,u1_left,u2_left,u3_left,u1_right,u2_right,u3_right);']); 
uicontrol(h,'Style','text','string','Plot variabel' ...
   ,'Position',rect1+[160,15,0,0]);
var_ui= uicontrol(h,'Style','popupmenu','string', ...
                   'density|momentum|energy|velocity|pressure' ...
   ,'Position',rect1+[160,0,0,0],'Callback', ['changepars;',...
                  'show(dx,plotvar,frame,sol,tvec,u1_left,u2_left,u3_left,u1_right,u2_right,u3_right);','fmat=[];']); 


%-- Plot parameters
uicontrol(h,'Style','text','string','Frame to Plot' ...
   ,'Position',rect1+[280,60,-20,0]);
uicontrol(h,'Style','text','string','No of Frames' ...
   ,'Position',rect1+[280,40,-20,0]);
plot_ui  = uicontrol(h,'Style','edit','String','0' ...
       ,'Position',rect2+[260,60,0,0]);
frame_ui  = uicontrol(h,'Style','edit','String',nframes ...
		      ,'Position',rect2+[260,40,0,0],'Callback', ...
		      ['sol=[];','fmat=[];']);




%-- Action buttons
rect1 = rect1+[430,0,0,0];
uicontrol(h,'Style','push','string','Solve' ...
	  ,'Position',rect1+[0,60,0,0],'Callback', ...
	  ['changepars;','[sol,tvec]=solve(dx,dt,method,' ...
           'nframes,T,u1_left,u2_left,u3_left,u1_right,u2_right,u3_right);', ...
           'nframes=length(tvec);','frame=nframes;' ... 
           ,'set(frame_ui,''String'',num2str(nframes));', ...
           'set(plot_ui,''String'',num2str(frame));', ...
           'show(dx,plotvar,frame,sol,tvec,u1_left,u2_left,' ...
            'u3_left,u1_right,u2_right,u3_right);','fmat=[];']); 
uicontrol(h,'Style','push','string','Plot' ...
	  ,'Position',rect1+[-150,20,-20,0],'Callback', ...
	  ['changepars;','f1=show(dx,plotvar,frame,sol,' ...
                    'tvec,u1_left,u2_left,u3_left,u1_right,' ...
                    'u2_right,u3_right);']);  
uicontrol(h,'Style','push','string','Movie' ...
	  ,'Position',rect1+[-150,0,-20,0],'Callback',['changepars;', ...
		    'moviedriver;']);
uicontrol(h,'Style','push','string','Inital data' ...
	  ,'Position',rect1+[0,40,0,0],'Callback','initpar;');
uicontrol(h,'Style','push','string','Exit' ...
	  ,'Position',rect1+[0,20,0,0],'Callback',['disp(''BYE'');', ...
		    'clear all;','close all;']);


%-- Initial conditions
changepars;
show(dx,plotvar,frame,sol,tvec,u1_left,u2_left,u3_left,u1_right, ...
     u2_right,u3_right); 
