%-- Initial parameters

  
  f3=figure(3); close(f3);
  f3=figure('Position',[450 400 400 80],'Name','Initial data', ...
	    'NumberTitle','off','MenuBar','none');


  uicontrol(f3,'Style','text','string','u1 left','Position',[20,50,50,20]);
  u1_left_ui  = uicontrol(f3,'Style','edit','string',num2str(u1_left),'Position',[70,50,50,20], ...
		       'Callback','changeinit;');
  uicontrol(f3,'Style','text','string','u2 left','Position',[20,30,50,20]);
  u2_left_ui  = uicontrol(f3,'Style','edit','string',num2str(u2_left),'Position',[70,30,50,20], ...
		       'Callback','changeinit;');
  uicontrol(f3,'Style','text','string','u3 left','Position',[20,10,50,20]);
  u3_left_ui  = uicontrol(f3,'Style','edit','string',num2str(u3_left),'Position',[70,10,50,20], ...
		       'Callback','changeinit;');

  uicontrol(f3,'Style','text','string','u1 right','Position',[150,50,50,20]);
  u1_right_ui  = uicontrol(f3,'Style','edit','string',num2str(u1_right),'Position',[200,50,50,20], ...
		       'Callback','changeinit;');
  uicontrol(f3,'Style','text','string','u2 right','Position',[150,30,50,20]);
  u2_right_ui  = uicontrol(f3,'Style','edit','string',num2str(u2_right),'Position',[200,30,50,20], ...
		       'Callback','changeinit;');
  uicontrol(f3,'Style','text','string','u3 right','Position',[150,10,50,20]);
  u3_right_ui  = uicontrol(f3,'Style','edit','string',num2str(u3_right),'Position',[200,10,50,20], ...
		       'Callback','changeinit;');
  
  uicontrol(f3,'Style','push','string','Set' ...
            ,'Position',[270,50,90,20],'Callback',['changeinit;','close(f3);', ...
                      'sol=[];','fmat=[];', 'frame=0;', ...
                      'set(plot_ui,''String'',num2str(frame));', ...
                      'show(dx,plotvar,frame,sol,tvec,u1_left,u2_left,u3_left,u1_right,u2_right,u3_right);']);    
  uicontrol(f3,'Style','push','string','Reset' ...
            ,'Position',[270,30,90,20],'Callback',['u1_right=0.125;', ...
                      'u2_right=0;','u3_right=0.25;',' u1_left=1;', ...
                      'u2_left=0;','u3_left=2.5;', ...
                      'close(f3);','sol=[];','fmat=[];','frame=0;', ...
                      'set(plot_ui,''String'',num2str(frame));', ...
                      'show(dx,plotvar,frame,sol,tvec,u1_left,u2_left,u3_left,u1_right,u2_right,u3_right);']);
  uicontrol(f3,'Style','push','string','Close' ...
            ,'Position',[270,10,90,20],'Callback','close(f3);');  

  return;
  